apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nodemvc
  name: nodemvc
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: nodemvc
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nodemvc
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH
              value: "false"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: example
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://root:example@mongo-db:27017/
            - name: REDIS_HOST
              value: cache
            - name: REDIS_PASSWORD
              value: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
            - name: REDIS_PORT
              value: "6379"
          image: prabuvillan/node-prabu-image
          name: nodemvc
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
